import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.team': 'Membres du labo',
    'nav.publications': 'Publications',
    'nav.events': 'Événements',
    'nav.contact': 'Contact',
    'nav.login': 'Se connecter',
    'nav.axes': 'Axes de Recherche',

    // Greetings
    'greet.morning': 'Bonjour',
    'greet.afternoon': 'Bonjour',
    'greet.evening': 'Bonsoir',

    // Home page
    'home.hero.title': 'Bienvenue au Laboratoire LIMTIC',
    'home.hero.subtitle': 'Laboratoire d\'Informatique, Modélisation et Traitement de l\'Information et de la Connaissance',
    'home.hero.publications': 'Nos Publications',
    'home.hero.team': 'Notre Équipe',
    'home.hero.contact': 'Nous Contacter',
    'home.stats.researchers': 'Membres permanents',
    'home.stats.publications': 'Publications scientifiques',
    'home.stats.phd': 'Doctorants en cours',
    'home.stats.events': 'Événements organisés',
    'home.axes.title': 'Nos Axes de Recherche',
    'home.axes.subtitle': 'Découvrez nos domaines d\'expertise et d\'innovation',
    'home.axes.viewAxis': 'Voir l\'axe',
    'home.publications.title': 'Publications Récentes',
    'home.publications.read': 'Lire',
    'home.events.title': 'Agenda',
    'home.events.view': 'Voir',
    'home.viewAll': 'Voir toutes',
    'home.viewAllEvents': 'Voir tous les événements',

    // Team page
    'team.title': 'Membres du Laboratoire',
    'team.subtitle': 'Découvrez les chercheurs, doctorants et mastériens du laboratoire LIMTIC',
    'team.labMembers': 'Membres du labo',
    'team.researchers': 'Chercheurs',
    'team.phd': 'Doctorants',
    'team.masters': 'Mastériens',
    'team.axes': 'Axes de Recherche',
    'team.viewProfile': 'Voir profil',
    'team.email': 'Email',
    'team.labTeam': 'Équipe du laboratoire',
    'team.membersCount': 'membres — chercheurs, doctorants et mastériens',
    'team.searchMember': 'Rechercher un membre...',
    'team.noMembers': 'Aucun membre trouvé',
    'team.breadcrumb': 'Accueil / Membres du laboratoire',
    'team.director': 'Directeur',
    'team.year': 'Année',
    'team.promotion': 'Promotion',
    'team.supervisor': 'Encadrant',

    // Publications
    'pub.title': 'Publications Scientifiques',
    'pub.myPublications': 'Mes publications',
    'pub.labPublications': 'Publications du labo',
    'pub.labPublicationsLong': 'Publications du laboratoire',
    'pub.managePublications': 'Gestion des Publications',
    'pub.manageAllPublications': 'Gérer toutes les publications du laboratoire',
    'pub.createNew': 'Créer une publication',
    'pub.newPublication': 'Nouvelle publication',
    'pub.editPublication': 'Modifier la publication',
    'pub.total': 'Total',
    'pub.journals': 'Journaux',
    'pub.conferences': 'Conférences',
    'pub.download': 'Télécharger PDF',
    'pub.viewDOI': 'Voir DOI',
    'pub.exportBibTeX': 'Exporter BibTeX',
    'pub.exportCSV': 'Exporter CSV',
    'pub.abstract': 'Résumé',
    'pub.keywords': 'Mots-clés',
    'pub.details': 'Détails',
    'pub.read': 'Lire',
    'pub.authors': 'Auteurs',
    'pub.venue': 'Revue / Conférence',
    'pub.doi': 'DOI',
    'pub.axis': 'Axe de recherche',
    'pub.visibility': 'Visibilité',
    'pub.public': 'Publique',
    'pub.private': 'Privée',
    'pub.internal': 'Interne uniquement',
    'pub.draft': 'Brouillon',
    'pub.drafts': 'Brouillons',
    'pub.submitted': 'Soumis',
    'pub.underReview': 'En révision',
    'pub.published': 'Publié',
    'pub.publishedCount': 'Publiées',
    'pub.rejected': 'Rejeté',
    'pub.rejectedCount': 'Rejetées',
    'pub.pending': 'En attente',
    'pub.approve': 'Approuver',
    'pub.reject': 'Rejeter',
    'pub.submit': 'Soumettre',
    'pub.submitForReview': 'Soumettre pour révision',
    'pub.submittedForReview': 'Publication soumise pour révision avec succès',
    'pub.rejectionReason': 'Motif de rejet',
    'pub.submittedBy': 'Soumis par',
    'pub.noPublications': 'Aucune publication trouvée',
    'pub.createFirst': 'Créez votre première publication !',
    'pub.noResults': 'Aucun résultat ne correspond à vos critères',
    'pub.searchPlaceholder': 'Rechercher une publication...',
    'pub.manageYourWork': 'Gérez et soumettez vos travaux scientifiques',
    'pub.submitYourWork': 'Soumettez et gérez vos travaux scientifiques',
    'pub.workflow': 'Workflow',
    'pub.workflowDesc': 'Créez un brouillon → Soumettez pour révision → L\'administration approuve et publie.',
    'pub.viewDetails': 'Voir les détails',
    'pub.publicationDetails': 'Détails de la publication',
    'pub.deleteConfirm': 'Supprimer cette publication',
    'pub.deleteMessage': 'Êtes-vous sûr de vouloir supprimer',
    'pub.deleteWarning': 'Cette action est irréversible.',
    'pub.submitConfirm': 'Soumettre pour révision',
    'pub.submitMessage': 'Vous ne pourrez plus la modifier pendant la révision.',
    'pub.typeRequired': 'Type de publication *',
    'pub.titleRequired': 'Titre *',
    'pub.axisRequired': 'Axe de recherche *',
    'pub.selectAxis': 'Sélectionner...',
    'pub.saveDraft': 'Créer le brouillon',
    'pub.modifiedSuccess': 'Publication modifiée avec succès',
    'pub.createdDraft': 'Publication créée en brouillon',
    'pub.deleted': 'Publication supprimée',
    'pub.deletePublication': 'Supprimer la publication',
    'pub.confirmDelete': 'Êtes-vous sûr de vouloir supprimer',
    'pub.confirmSubmit': 'Soumettre',
    'pub.cannotDeleteUnderReview': 'Impossible de supprimer une publication en révision',
    'pub.cannotModifyDuringReview': '? Vous ne pourrez plus la modifier pendant la révision.',

    // Publication Types
    'pubType.journal': 'Article de journal',
    'pubType.confInt': 'Conférence internationale',
    'pubType.confNat': 'Conférence nationale',
    'pubType.chapter': 'Chapitre d\'ouvrage',
    'pubType.report': 'Rapport technique',

    // Roles
    'role.researcher': 'Chercheur',
    'role.phd': 'Doctorant',
    'role.master': 'Mastérien',

    // Events
    'event.title': 'Événements',
    'event.labEvents': 'Événements du laboratoire',
    'event.manageEvents': 'Gestion des Événements',
    'event.manageAllEvents': 'Gérer tous les événements du laboratoire',
    'event.createNew': 'Créer un événement',
    'event.newEvent': 'Nouvel événement',
    'event.editEvent': 'Modifier l\'événement',
    'event.upcoming': 'À venir',
    'event.upcomingEvents': 'Prochains événements',
    'event.ongoing': 'En cours',
    'event.past': 'Passés',
    'event.pastEvents': 'Événements passés',
    'event.viewDetails': 'Voir les détails',
    'event.description': 'Description',
    'event.program': 'Programme',
    'event.speakers': 'Intervenants',
    'event.location': 'Lieu',
    'event.date': 'Date',
    'event.photos': 'Photos de l\'événement',
    'event.eventDetails': 'Détails de l\'événement',
    'event.noEvents': 'Aucun événement trouvé',
    'event.searchPlaceholder': 'Rechercher un événement...',
    'event.seminarsWorkshops': 'Séminaires, conférences, workshops et soutenances',

    // Lab info
    'lab.fullName': 'Laboratoire d\'Informatique, Modélisation et Traitement de l\'Information et de la Connaissance',
    'lab.shortName': 'Laboratoire de Recherche',
    'lab.address': 'Institut Supérieur d\'Informatique, Université de Tunis El Manar',
    'lab.addressFull': 'Institut Supérieur d\'Informatique\nUniversité de Tunis El Manar\n2010 Tunis, Tunisie',
    'lab.copyright': '© 2026 LIMTIC - Laboratoire de Recherche',

    // Notifications examples
    'notif.pubApproved': 'Nouvelle publication approuvée',
    'notif.eventTomorrow': 'Événement demain : Séminaire IA',
    'notif.profileUpdated': 'Mise à jour du profil confirmée',
    'notif.ago2h': 'Il y a 2h',
    'notif.ago5h': 'Il y a 5h',
    'notif.yesterday': 'Hier',

    // Dashboard common
    'dash.overview': 'Dashboard',
    'dash.dashboard': 'Dashboard',
    'dash.profile': 'Mon profil',
    'dash.myProfile': 'Mon profil',
    'dash.welcomeDr': 'Bienvenue, Dr.',
    'dash.welcomeUser': 'Bienvenue,',
    'dash.welcomeVisitor': 'Bienvenue dans l\'espace visiteur',
    'dash.inProgress': 'En cours',
    'dash.completed': 'Terminé',
    'dash.pending': 'En attente',
    'dash.overviewTitle': 'Vue d\'ensemble',
    'dash.myPublications': 'Mes publications',
    'dash.myRecentPublications': 'Mes publications récentes',
    'dash.recentPublications': 'Publications récentes',
    'dash.lastLabPublications': 'Dernières publications du labo',
    'dash.activeSupervisions': 'Encadrements actifs',
    'dash.viewAll': 'Voir tout',
    'dash.viewAllPublications': 'Voir toutes les publications',
    'dash.phdSupervised': 'Doctorants encadrés',
    'dash.mastersSupervised': 'Mastériens encadrés',
    'dash.publications': 'Mes publications',
    'dash.students': 'Mes encadrements',
    'dash.supervisions': 'Mes encadrements',
    'dash.notifications': 'Notifications',
    'dash.users': 'Utilisateurs',
    'dash.events': 'Événements',
    'dash.upcomingEvents': 'Événements à venir',
    'dash.members': 'Membres',
    'dash.team': 'Équipe',
    'dash.axes': 'Axes de recherche',
    'dash.researchAxes': 'Axes de recherche',
    'dash.statistics': 'Statistiques',
    'dash.audit': 'Journal d\'audit',
    'dash.settings': 'Paramètres',
    'dash.logout': 'Se déconnecter',
    'dash.welcome': 'Bienvenue',
    'dash.welcomeBack': 'Bienvenue',
    'dash.createPublication': 'Créer une publication',
    'dash.createNewPublication': 'Créer une nouvelle publication',
    'dash.createEvent': 'Créer un événement',
    'dash.createUser': 'Créer un utilisateur',
    'dash.addMember': 'Ajouter un membre',
    'dash.allPublications': 'Publications du labo',
    'dash.quickAccess': 'Accès rapide',
    'dash.myResearchAxis': 'Mon axe de recherche',
    'dash.exploreAllAxes': 'Explorer tous les axes',
    'dash.viewLabTeam': 'Voir l\'équipe du labo',
    'dash.consultEvents': 'Consulter les événements',
    'dash.manageUsers': 'Gérer les utilisateurs',
    'dash.viewStatistics': 'Voir les statistiques',
    'dash.auditLog': 'Journal d\'audit',
    'dash.systemSettings': 'Paramètres système',
    'dash.superadminDashboard': 'Tableau de bord SuperAdmin — LIMTIC',
    'dash.pendingPublications': 'Publications en attente',
    'dash.noPendingPublications': 'Aucune publication en attente',
    'dash.recentActivity': 'Activité récente',
    'dash.adminDashboard': 'Tableau de bord — Admin',
    'dash.manageLabContent': 'Gérez les publications, événements et membres du laboratoire',
    'dash.pendingPublicationsCount': 'Publications en attente',
    'dash.activeMembers': 'Membres actifs',
    'dash.quickActions': 'Actions rapides',
    'dash.managePublications': 'Gérer les publications',
    'dash.manageEvents': 'Gérer les événements',
    'dash.manageMembers': 'Gérer les membres',
    'dash.manageAxes': 'Gérer les axes',
    'dash.expectedParticipants': 'participants attendus',

    // Profile
    'profile.title': 'Mon profil',
    'profile.personalInfo': 'Informations personnelles',
    'profile.firstName': 'Prénom',
    'profile.lastName': 'Nom',
    'profile.email': 'Email',
    'profile.phone': 'Téléphone',
    'profile.role': 'Rôle',
    'profile.bio': 'Biographie',
    'profile.researchInterests': 'Intérêts de recherche',
    'profile.academicInfo': 'Informations académiques',
    'profile.supervisor': 'Encadrant',
    'profile.thesisSupervisor': 'Directeur de thèse',
    'profile.thesisTitle': 'Titre de la thèse',
    'profile.myThesis': 'Ma thèse',
    'profile.myProject': 'Mon mémoire',
    'profile.projectTitle': 'Titre du projet',
    'profile.enrollmentYear': 'Année d\'inscription',
    'profile.enrollmentLabel': 'Inscription',
    'profile.academicYear': 'Année académique',
    'profile.promotionLabel': 'Promotion',
    'profile.speciality': 'Spécialité',
    'profile.masterSpeciality': 'Spécialité Master',
    'profile.office': 'Bureau',
    'profile.updateSuccess': 'Profil mis à jour avec succès',
    'profile.updateProfile': 'Mettre à jour le profil',
    'profile.profilePhoto': 'Photo de profil',
    'profile.changePhoto': 'Changer la photo',
    'profile.attachedAxis': 'Axe de rattachement',

    // Users Management
    'users.title': 'Gestion des Utilisateurs',
    'users.manageUsers': 'Gérer les comptes utilisateurs',
    'users.createUser': 'Créer un utilisateur',
    'users.editUser': 'Modifier l\'utilisateur',
    'users.totalUsers': 'Total utilisateurs',
    'users.activeUsers': 'Actifs',
    'users.pendingUsers': 'En attente',
    'users.searchPlaceholder': 'Rechercher un utilisateur...',
    'users.noUsers': 'Aucun utilisateur trouvé',
    'users.deleteConfirm': 'Supprimer cet utilisateur',
    'users.deleteMessage': 'Êtes-vous sûr de vouloir supprimer cet utilisateur ?',
    'users.usersRegistered': 'utilisateurs enregistrés',
    'users.total': 'Total',
    'users.researchers': 'Chercheurs',
    'users.phdStudents': 'Doctorants',
    'users.masters': 'Mastériens',
    'users.visitors': 'Visiteurs',
    'users.inactive': 'Inactifs',
    'users.searchByNameEmail': 'Rechercher par nom ou email...',
    'users.user': 'Utilisateur',
    'users.role': 'Rôle',
    'users.specialization': 'Spécialisation',
    'users.status': 'Statut',
    'users.lastLogin': 'Dernière connexion',
    'users.actions': 'Actions',
    'users.activate': 'Activer',
    'users.deactivate': 'Désactiver',
    'users.active': 'Actif',
    'users.since': 'Depuis le',
    'users.userCreatedAs': 'Utilisateur créé en tant que Visiteur. Configurez maintenant son rôle et ses informations.',
    'users.step1': 'Étape 1/2 : Informations de base',
    'users.step2': 'Étape 2/2 : Rôle et informations spécifiques',
    'users.firstName': 'Prénom',
    'users.lastName': 'Nom',
    'users.password': 'Mot de passe',
    'users.confirmPassword': 'Confirmer le mot de passe',
    'users.next': 'Suivant',
    'users.finish': 'Terminer',
    'users.userRole': 'Rôle de l\'utilisateur',
    'users.visitor': 'Visiteur (accès lecture seule)',
    'users.master': 'Mastérien',
    'users.phd': 'Doctorant',
    'users.researcher': 'Chercheur',
    'users.admin': 'Admin',
    'users.superAdmin': 'SuperAdmin',
    'users.researchAxis': 'Axe de recherche',
    'users.selectAxis': 'Sélectionner un axe de recherche',
    'users.academicProfiles': 'Profils académiques (optionnel)',
    'users.orcid': 'ORCID',
    'users.googleScholar': 'Google Scholar',
    'users.researchGate': 'ResearchGate',
    'users.linkedin': 'LinkedIn',
    'users.personalWebsite': 'Site web personnel',
    'users.enrollmentYear': 'Année académique',
    'users.supervisor': 'Encadrant',
    'users.selectSupervisor': 'Sélectionner un encadrant',
    'users.thesisTitle': 'Sujet de thèse',
    'users.projectTitle': 'Sujet du projet',
    'users.fillAllFields': 'Veuillez remplir tous les champs obligatoires',
    'users.passwordRequired': 'Le mot de passe est requis',
    'users.userModified': 'Utilisateur modifié avec succès !',
    'users.userConfigured': 'Utilisateur configuré avec succès !',
    'users.userDeleted': 'Utilisateur supprimé',
    'users.userActivated': 'activé',
    'users.userDeactivated': 'désactivé',
    'users.deleteUserConfirm': 'Supprimer l\'utilisateur',
    'users.deleteUserMessage': 'Êtes-vous sûr de vouloir supprimer',
    'users.irreversible': 'Cette action est irréversible.',
    'users.defaultVisitor': 'L\'utilisateur sera créé par défaut avec le rôle',
    'users.configureNext': 'Vous pourrez configurer son rôle et ses informations spécifiques à l\'étape suivante.',
    'users.modifyUser': 'Modifier l\'utilisateur',
    'users.specificInfo': 'Modifier les informations spécifiques',
    'users.configureUser': 'Configurer l\'utilisateur',
    'users.rank': 'Grade académique',
    'users.rankPlaceholder': 'Ex: Maître de conférences, Professeur...',
    'users.errorOccurred': 'Une erreur est survenue',
    'users.invalidYear': 'Année d\'inscription invalide',
    'users.fillRequiredFields': 'Veuillez remplir tous les champs obligatoires',

    // Supervisions (Encadrements)
    'supervision.title': 'Mes Encadrements',
    'supervision.phd': 'Doctorants',
    'supervision.master': 'Mastériens',
    'supervision.add': 'Ajouter Encadrement',
    'supervision.details': 'Détails',
    'supervision.studentProfile': 'Profil de l\'étudiant',
    'supervision.close': 'Fermer',
    'supervision.enrolled': 'Inscrit en',
    'supervision.promotion': 'Promotion',
    'supervision.thesisTitle': 'Sujet de thèse',
    'supervision.projectTitle': 'Sujet de mémoire',
    'supervision.none': 'Aucun encadrement dans cette catégorie',
    'supervision.selectType': 'Sélectionnez le type d\'encadrement',
    'supervision.addSupervision': 'Ajouter un encadrement',
    'supervision.phdStudent': 'Doctorant',
    'supervision.phdDescription': 'Encadrer un étudiant en doctorat',
    'supervision.masterStudent': 'Mastérien',
    'supervision.masterDescription': 'Encadrer un étudiant en master',
    'supervision.selectStudent': 'Sélectionner l\'étudiant',
    'supervision.chooseStudent': 'Choisir un étudiant',
    'supervision.thesisSubject': 'Sujet de thèse',
    'supervision.projectSubject': 'Sujet de mémoire',
    'supervision.researchSubject': 'Titre du sujet de recherche...',
    'supervision.enrollmentYear': 'Année d\'inscription',
    'supervision.academicYear': 'Promotion',
    'supervision.modifySupervision': 'Modifier l\'encadrement',
    'supervision.supervisionModified': 'Encadrement modifié avec succès',
    'supervision.supervisionDeleted': 'Encadrement supprimé',
    'supervision.deleteSupervision': 'Supprimer l\'encadrement',
    'supervision.deleteMessage': 'Êtes-vous sûr de vouloir retirer',
    'supervision.fromSupervisions': 'de vos encadrements ? Cette action est irréversible.',
    'supervision.supervisionAdded': 'ajouté avec succès',
    'supervision.publications': 'publication',
    'supervision.publications_plural': 'publications',

    // Publications Page
    'pubPage.title': 'Publications Scientifiques',
    'pubPage.subtitle': 'Découvrez nos travaux de recherche publiés',
    'pubPage.breadcrumb': 'Accueil / Publications',
    'pubPage.total': 'Total',
    'pubPage.journals': 'Journaux',
    'pubPage.conferences': 'Conférences',
    'pubPage.searchPlaceholder': 'Rechercher par titre, auteur ou venue...',
    'pubPage.noPublications': 'Aucune publication trouvée',
    'pubPage.noResults': 'Aucun résultat ne correspond à vos critères de recherche',
    'pubPage.viewDetails': 'Voir détails',
    'pubPage.typePublication': 'Type de publication',
    'pubPage.journalArticles': 'Articles de journal',
    'pubPage.ranking': 'Classement',
    'pubPage.q1': 'Q1',
    'pubPage.q2': 'Q2',
    'pubPage.coreAStar': 'CORE A*',
    'pubPage.coreA': 'CORE A',
    'pubPage.year': 'Année',
    'pubPage.axis': 'Axe de recherche',
    'pubPage.aiAxis': 'Intelligence Artificielle',
    'pubPage.securityAxis': 'Sécurité Informatique',
    'pubPage.systemsAxis': 'Systèmes Distribués',
    'pubPage.visionAxis': 'Vision par Ordinateur',
    'pubPage.journalArticle': 'Article de journal',
    'pubPage.conference': 'Conférence',

    // Events Page
    'eventPage.title': 'Événements',
    'eventPage.subtitle': 'Découvrez nos séminaires, ateliers et conférences',
    'eventPage.breadcrumb': 'Accueil / Événements',
    'eventPage.upcoming': 'À venir',
    'eventPage.ongoing': 'En cours',
    'eventPage.past': 'Passés',
    'eventPage.photos': 'Photos',
    'eventPage.noEvents': 'Aucun événement',
    'eventPage.comeBackLater': 'Revenez plus tard pour découvrir nos prochains événements',
    'eventPage.speakers': 'intervenant',
    'eventPage.speakers_plural': 'intervenants',
    'eventPage.viewDetails': 'Voir les détails',
    'eventPage.photosAvailable': 'Photos disponibles',
    'eventPage.seminar': 'SÉMINAIRE',
    'eventPage.workshop': 'ATELIER',
    'eventPage.conference': 'CONFÉRENCE',
    'eventPage.studyDay': 'JOURNÉE D\'ÉTUDE',

    // Statistics
    'stats.title': 'Statistiques',
    'stats.overview': 'Vue d\'ensemble du laboratoire',
    'stats.totalPublications': 'Total Publications',
    'stats.thisYear': 'Cette année',
    'stats.activeMembers': 'Membres Actifs',
    'stats.upcomingEvents': 'Événements à venir',
    'stats.researchAxes': 'Axes de recherche',
    'stats.publicationsByYear': 'Publications par année',
    'stats.publicationsByType': 'Publications par type',
    'stats.publicationsByAxis': 'Publications par axe',
    'stats.topAuthors': 'Auteurs les plus productifs',

    // Audit
    'audit.title': 'Journal d\'audit',
    'audit.systemActivity': 'Activité et historique du système',
    'audit.action': 'Action',
    'audit.user': 'Utilisateur',
    'audit.details': 'Détails',
    'audit.timestamp': 'Horodatage',
    'audit.searchPlaceholder': 'Rechercher dans l\'audit...',

    // Axes de recherche
    'axes.title': 'Axes de Recherche',
    'axes.ourAxes': 'Nos Axes de Recherche',
    'axes.discoverDomains': 'Découvrez nos domaines d\'expertise et d\'innovation',
    'axes.manageAxes': 'Gestion des Axes de Recherche',
    'axes.createAxis': 'Créer un axe',
    'axes.editAxis': 'Modifier l\'axe',
    'axes.viewDetails': 'Voir détails',
    'axes.members': 'Membres',
    'axes.publicationsCount': 'publications',
    'axes.themes': 'Thèmes de recherche',
    'axes.responsible': 'Responsable',
    'axes.relatedPublications': 'Publications liées',
    'axes.breadcrumb': 'Accueil / Axes de Recherche',
    'axes.activeAxes': 'Axes actifs',
    'axes.researchers': 'Chercheurs',
    'axes.exploreAxes': 'Explorez les axes de recherche du laboratoire LIMTIC',
    'axes.viewPublications': 'Voir les publications',
    'axes.totalMembers': 'Membres total',
    'axes.totalPublications': 'Publications total',
    'axes.searchPlaceholder': 'Rechercher un axe, thème ou responsable...',
    'axes.searchPlaceholderShort': 'Rechercher un axe ou thème...',
    'axes.noAxesFound': 'Aucun axe trouvé pour',
    'axes.noAxesFoundGeneric': 'Aucun axe trouvé',
    'axes.noResults': 'Aucun résultat ne correspond à vos critères',
    'axes.axisNotFound': 'Axe non trouvé',
    'axes.backToAxes': 'Retour aux axes de recherche',
    'axes.axisHead': 'Responsable d\'axe',
    'axes.axisMembers': 'Membres de l\'axe',
    'axes.axisPublications': 'Publications de l\'axe',
    'axes.themesTitle': 'Thématiques de recherche',
    'axes.explorePublications': 'Explorer les publications',
    'axes.viewAllPublications': 'Voir toutes les publications',
    'axes.scientificPublications': 'Publications scientifiques',
    'axes.myAxis': 'Mon axe',
    'axes.myAxisAttachment': 'Mon axe de rattachement',
    'axes.myThesisAxis': 'Mon axe de thèse',
    'axes.youAreAttached': 'Vous êtes rattaché à cet axe',
    'axes.youAreAttachedThesis': 'Vous êtes rattaché à cet axe via votre thèse',
    'axes.axesCount': 'Axes de recherche',
    'axes.manageLabAxes': 'Gérer les axes de recherche du laboratoire',
    'axes.axisDeleted': 'Axe supprimé avec succès',
    'axes.deleteAxis': 'Supprimer cet axe de recherche',
    'axes.deleteMessage': 'Êtes-vous sûr de vouloir supprimer',
    'axes.deleteWarning': 'Cette action est irréversible et affectera',
    'axes.membersAnd': 'membres et',
    'axes.createAxisTitle': 'Créer un axe de recherche',
    'axes.editAxisTitle': 'Modifier l\'axe de recherche',
    'axes.axisTitle': 'Titre',
    'axes.description': 'Description',
    'axes.descriptionPlaceholder': 'Description détaillée de l\'axe de recherche...',
    'axes.responsibleSelect': 'Sélectionner un responsable',
    'axes.thematics': 'Thématiques',
    'axes.thematicsPlaceholder': 'Tapez une thématique et appuyez sur Entrée',
    'axes.addTheme': 'Ajouter',
    'axes.color': 'Couleur',
    'axes.colorBlue': 'Bleu',
    'axes.colorRed': 'Rouge',
    'axes.colorTeal': 'Turquoise',
    'axes.colorGreen': 'Vert',
    'axes.colorOrange': 'Orange',
    'axes.axisCreated': 'Axe créé avec succès!',
    'axes.axisModified': 'Axe modifié avec succès!',
    'axes.errorLoading': 'Erreur lors du chargement des axes',
    'axes.tryAgainLater': 'Veuillez réessayer plus tard',
    'axes.notAssigned': 'Non assigné',
    'axes.viewProfile': 'Voir le profil',

    // Contact
    'contact.title': 'Contactez-nous',
    'contact.name': 'Nom complet',
    'contact.email': 'Email',
    'contact.subject': 'Sujet',
    'contact.message': 'Message',
    'contact.send': 'Envoyer le message',
    'contact.messageSent': 'Message envoyé avec succès!',
    'contact.address': 'Adresse',
    'contact.phone': 'Téléphone',
    'contact.followUs': 'Suivez-nous',
    'contact.getInTouch': 'Entrer en contact',
    'contact.contactInfo': 'Informations de contact',

    // Login & Auth
    'login.title': 'Connexion',
    'login.secure': 'Espace sécurisé',
    'login.secureBackoffice': 'Connexion au back-office LIMTIC',
    'login.password': 'Mot de passe',
    'login.forgotPassword': 'Mot de passe oublié?',
    'login.rememberMe': 'Se souvenir de moi',
    'login.submit': 'Se connecter',
    'login.backToHome': 'Retour à l\'accueil',
    'login.testAccounts': 'Comptes de test:',
    'login.connecting': 'Connexion...',
    'login.connectionSuccess': 'Connexion réussie!',
    'login.connectionError': 'Erreur de connexion',
    'forgotPassword.title': 'Mot de passe oublié',
    'forgotPassword.enterEmail': 'Entrez votre email',
    'forgotPassword.sendCode': 'Envoyer le code',
    'forgotPassword.enterCode': 'Entrez le code',
    'forgotPassword.verify': 'Vérifier',
    'forgotPassword.verification': 'Vérification',
    'forgotPassword.newPassword': 'Nouveau mot de passe',
    'forgotPassword.newPasswordTitle': 'Nouveau mot de passe',
    'forgotPassword.confirmPassword': 'Confirmer le mot de passe',
    'forgotPassword.resetPassword': 'Réinitialiser',
    'forgotPassword.success': 'Succès',
    'forgotPassword.successMessage': 'Votre mot de passe a été réinitialisé',
    'forgotPassword.backToLogin': 'Retour à la connexion',
    'forgotPassword.emailSubtitle': 'Entrez votre email pour recevoir un code de vérification',
    'forgotPassword.otpSubtitle': 'Un code à 6 chiffres a été envoyé à',
    'forgotPassword.passwordSubtitle': 'Choisissez un nouveau mot de passe sécurisé',
    'forgotPassword.resendCode': 'Renvoyer le code',
    'forgotPassword.emailAddress': 'Adresse email',
    'forgotPassword.verifying': 'Vérification...',
    'forgotPassword.verifyCode': 'Vérifier le code',
    'forgotPassword.sending': 'Envoi en cours...',
    'forgotPassword.backToLogin2': 'Retour à la connexion',
    'forgotPassword.enter6Digits': 'Entrez le code à 6 chiffres',
    'forgotPassword.demoCode': 'Pour cette démo, utilisez le code:',
    'forgotPassword.changeEmail': 'Modifier l\'email',
    'forgotPassword.resetting': 'Réinitialisation...',
    'forgotPassword.passwordPlaceholder': 'Minimum 8 caractères',
    'forgotPassword.confirmPlaceholder': 'Retapez le mot de passe',
    'forgotPassword.passwordRequirements': 'Le mot de passe doit contenir au moins 8 caractères',
    'forgotPassword.newCodeSent': 'Un nouveau code a été envoyé',
    'forgotPassword.errorEmail': 'Veuillez entrer votre adresse email',
    'forgotPassword.errorCode': 'Veuillez entrer le code à 6 chiffres',
    'forgotPassword.errorInvalidCode': 'Code invalide.',
    'forgotPassword.errorFields': 'Veuillez remplir tous les champs',
    'forgotPassword.errorPasswordMatch': 'Les mots de passe ne correspondent pas',
    'forgotPassword.errorPasswordLength': 'Le mot de passe doit contenir au moins 8 caractères',
    'forgotPassword.codeSent': 'Un code de vérification a été envoyé à votre email',
    'forgotPassword.codeVerified': 'Code vérifié avec succès',
    'forgotPassword.passwordResetSuccess': 'Mot de passe réinitialisé avec succès',
    'forgotPassword.loginNow': 'Se connecter maintenant',
    'forgotPassword.redirecting': 'Vous allez être redirigé vers la page de connexion...',

    // Theme
    'theme.dark': 'Mode sombre',
    'theme.light': 'Mode clair',

    // Footer
    'footer.quickLinks': 'Liens Rapides',
    'footer.contact': 'Contact',
    'footer.followUs': 'Suivez-nous',
    'footer.legal': 'Mentions légales',
    'footer.privacy': 'Confidentialité',
    'footer.backToTop': 'Haut de page',
    'footer.allRights': 'Tous droits réservés.',

    // Common UI
    'common.save': 'Sauvegarder',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.modify': 'Modifier',
    'common.create': 'Créer',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.filters': 'Filtres',
    'common.status': 'Statut',
    'common.actions': 'Actions',
    'common.year': 'Année',
    'common.type': 'Type',
    'common.loading': 'Chargement...',
    'common.error': 'Une erreur est survenue',
    'common.success': 'Succès',
    'common.confirm': 'Confirmer',
    'common.close': 'Fermer',
    'common.view': 'Voir',
    'common.viewAll': 'Voir tout',
    'common.seeAll': 'Voir toutes',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.submit': 'Soumettre',
    'common.export': 'Exporter',
    'common.import': 'Importer',
    'common.download': 'Télécharger',
    'common.upload': 'Téléverser',
    'common.add': 'Ajouter',
    'common.remove': 'Retirer',
    'common.update': 'Mettre à jour',
    'common.send': 'Envoyer',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.all': 'Tous',
    'common.none': 'Aucun',
    'common.other': 'Autre',
    'common.optional': 'Optionnel',
    'common.required': 'Obligatoire',
    'common.select': 'Sélectionner',
    'common.selected': 'Sélectionné',
    'common.total': 'Total',
    'common.showing': 'Affichage',
    'common.of': 'de',
    'common.results': 'résultats',
    'common.noResults': 'Aucun résultat',
    'common.noData': 'Aucune donnée',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.team': 'Lab Members',
    'nav.publications': 'Publications',
    'nav.events': 'Events',
    'nav.contact': 'Contact',
    'nav.login': 'Sign in',
    'nav.axes': 'Research Areas',

    // Greetings
    'greet.morning': 'Good morning',
    'greet.afternoon': 'Good afternoon',
    'greet.evening': 'Good evening',

    // Home page
    'home.hero.title': 'Welcome to LIMTIC Laboratory',
    'home.hero.subtitle': 'Laboratory of Computer Science, Modeling and Information and Knowledge Processing',
    'home.hero.publications': 'Our Publications',
    'home.hero.team': 'Our Team',
    'home.hero.contact': 'Contact Us',
    'home.stats.researchers': 'Permanent members',
    'home.stats.publications': 'Scientific publications',
    'home.stats.phd': 'PhD students in progress',
    'home.stats.events': 'Events organized',
    'home.axes.title': 'Our Research Areas',
    'home.axes.subtitle': 'Discover our domains of expertise and innovation',
    'home.axes.viewAxis': 'View area',
    'home.publications.title': 'Recent Publications',
    'home.publications.read': 'Read',
    'home.events.title': 'Calendar',
    'home.events.view': 'View',
    'home.viewAll': 'View all',
    'home.viewAllEvents': 'View all events',

    // Team page
    'team.title': 'Laboratory Members',
    'team.subtitle': 'Meet the researchers, PhD students and Master\'s students of LIMTIC laboratory',
    'team.labMembers': 'Lab members',
    'team.researchers': 'Researchers',
    'team.phd': 'PhD Students',
    'team.masters': 'Master\'s Students',
    'team.axes': 'Research Areas',
    'team.viewProfile': 'View profile',
    'team.email': 'Email',
    'team.labTeam': 'Lab team',
    'team.membersCount': 'members — researchers, PhD students and Master\'s students',
    'team.searchMember': 'Search for a member...',
    'team.noMembers': 'No members found',
    'team.breadcrumb': 'Home / Lab Members',
    'team.director': 'Director',
    'team.year': 'Year',
    'team.promotion': 'Cohort',
    'team.supervisor': 'Supervisor',

    // Publications
    'pub.title': 'Scientific Publications',
    'pub.myPublications': 'My publications',
    'pub.labPublications': 'Lab publications',
    'pub.labPublicationsLong': 'Laboratory publications',
    'pub.managePublications': 'Publications Management',
    'pub.manageAllPublications': 'Manage all laboratory publications',
    'pub.createNew': 'Create publication',
    'pub.newPublication': 'New publication',
    'pub.editPublication': 'Edit publication',
    'pub.total': 'Total',
    'pub.journals': 'Journals',
    'pub.conferences': 'Conferences',
    'pub.download': 'Download PDF',
    'pub.viewDOI': 'View DOI',
    'pub.exportBibTeX': 'Export BibTeX',
    'pub.exportCSV': 'Export CSV',
    'pub.abstract': 'Abstract',
    'pub.keywords': 'Keywords',
    'pub.details': 'Details',
    'pub.read': 'Read',
    'pub.authors': 'Authors',
    'pub.venue': 'Journal / Conference',
    'pub.doi': 'DOI',
    'pub.axis': 'Research area',
    'pub.visibility': 'Visibility',
    'pub.public': 'Public',
    'pub.private': 'Private',
    'pub.internal': 'Internal only',
    'pub.draft': 'Draft',
    'pub.drafts': 'Drafts',
    'pub.submitted': 'Submitted',
    'pub.underReview': 'Under review',
    'pub.published': 'Published',
    'pub.publishedCount': 'Published',
    'pub.rejected': 'Rejected',
    'pub.rejectedCount': 'Rejected',
    'pub.pending': 'Pending',
    'pub.approve': 'Approve',
    'pub.reject': 'Reject',
    'pub.submit': 'Submit',
    'pub.submitForReview': 'Submit for review',
    'pub.submittedForReview': 'Publication submitted for review successfully',
    'pub.rejectionReason': 'Rejection reason',
    'pub.submittedBy': 'Submitted by',
    'pub.noPublications': 'No publications found',
    'pub.createFirst': 'Create your first publication!',
    'pub.noResults': 'No results match your criteria',
    'pub.searchPlaceholder': 'Search for a publication...',
    'pub.manageYourWork': 'Manage and submit your scientific work',
    'pub.submitYourWork': 'Submit and manage your scientific work',
    'pub.workflow': 'Workflow',
    'pub.workflowDesc': 'Create a draft → Submit for review → Administration approves and publishes.',
    'pub.viewDetails': 'View details',
    'pub.publicationDetails': 'Publication details',
    'pub.deleteConfirm': 'Delete this publication',
    'pub.deleteMessage': 'Are you sure you want to delete',
    'pub.deleteWarning': 'This action is irreversible.',
    'pub.submitConfirm': 'Submit for review',
    'pub.submitMessage': 'You will not be able to modify it during review.',
    'pub.typeRequired': 'Publication type *',
    'pub.titleRequired': 'Title *',
    'pub.axisRequired': 'Research area *',
    'pub.selectAxis': 'Select...',
    'pub.saveDraft': 'Create draft',
    'pub.modifiedSuccess': 'Publication modified successfully',
    'pub.createdDraft': 'Publication created as draft',
    'pub.deleted': 'Publication deleted',
    'pub.deletePublication': 'Delete publication',
    'pub.confirmDelete': 'Are you sure you want to delete',
    'pub.confirmSubmit': 'Submit',
    'pub.cannotDeleteUnderReview': 'Cannot delete a publication under review',
    'pub.cannotModifyDuringReview': '? You will not be able to modify it during review.',

    // Publication Types
    'pubType.journal': 'Journal article',
    'pubType.confInt': 'International conference',
    'pubType.confNat': 'National conference',
    'pubType.chapter': 'Book chapter',
    'pubType.report': 'Technical report',

    // Roles
    'role.researcher': 'Researcher',
    'role.phd': 'PhD Student',
    'role.master': 'Master\'s Student',

    // Events
    'event.title': 'Events',
    'event.labEvents': 'Laboratory events',
    'event.manageEvents': 'Events Management',
    'event.manageAllEvents': 'Manage all laboratory events',
    'event.createNew': 'Create event',
    'event.newEvent': 'New event',
    'event.editEvent': 'Edit event',
    'event.upcoming': 'Upcoming',
    'event.upcomingEvents': 'Upcoming events',
    'event.ongoing': 'Ongoing',
    'event.past': 'Past',
    'event.pastEvents': 'Past events',
    'event.viewDetails': 'View details',
    'event.description': 'Description',
    'event.program': 'Program',
    'event.speakers': 'Speakers',
    'event.location': 'Location',
    'event.date': 'Date',
    'event.photos': 'Event photos',
    'event.eventDetails': 'Event details',
    'event.noEvents': 'No events found',
    'event.searchPlaceholder': 'Search for an event...',
    'event.seminarsWorkshops': 'Seminars, conferences, workshops and thesis defenses',

    // Lab info
    'lab.fullName': 'Laboratory of Computer Science, Modeling and Information and Knowledge Processing',
    'lab.shortName': 'Research Laboratory',
    'lab.address': 'Higher Institute of Computer Science, University of Tunis El Manar',
    'lab.addressFull': 'Higher Institute of Computer Science\nUniversity of Tunis El Manar\n2010 Tunis, Tunisia',
    'lab.copyright': '© 2026 LIMTIC - Research Laboratory',

    // Notifications examples
    'notif.pubApproved': 'New publication approved',
    'notif.eventTomorrow': 'Event tomorrow: AI Seminar',
    'notif.profileUpdated': 'Profile update confirmed',
    'notif.ago2h': '2h ago',
    'notif.ago5h': '5h ago',
    'notif.yesterday': 'Yesterday',

    // Dashboard common
    'dash.overview': 'Dashboard',
    'dash.dashboard': 'Dashboard',
    'dash.profile': 'My profile',
    'dash.myProfile': 'My profile',
    'dash.welcomeDr': 'Welcome, Dr.',
    'dash.welcomeUser': 'Welcome,',
    'dash.welcomeVisitor': 'Welcome to visitor area',
    'dash.inProgress': 'In progress',
    'dash.completed': 'Completed',
    'dash.pending': 'Pending',
    'dash.overviewTitle': 'Overview',
    'dash.myPublications': 'My publications',
    'dash.myRecentPublications': 'My recent publications',
    'dash.recentPublications': 'Recent publications',
    'dash.lastLabPublications': 'Latest lab publications',
    'dash.activeSupervisions': 'Active supervisions',
    'dash.viewAll': 'View all',
    'dash.viewAllPublications': 'View all publications',
    'dash.phdSupervised': 'PhD supervised',
    'dash.mastersSupervised': 'Master\'s supervised',
    'dash.publications': 'My publications',
    'dash.students': 'My supervisions',
    'dash.supervisions': 'My supervisions',
    'dash.notifications': 'Notifications',
    'dash.users': 'Users',
    'dash.events': 'Events',
    'dash.upcomingEvents': 'Upcoming events',
    'dash.members': 'Members',
    'dash.team': 'Team',
    'dash.axes': 'Research areas',
    'dash.researchAxes': 'Research areas',
    'dash.statistics': 'Statistics',
    'dash.audit': 'Audit log',
    'dash.settings': 'Settings',
    'dash.logout': 'Logout',
    'dash.welcome': 'Welcome',
    'dash.welcomeBack': 'Welcome back',
    'dash.createPublication': 'Create publication',
    'dash.createNewPublication': 'Create a new publication',
    'dash.createEvent': 'Create event',
    'dash.createUser': 'Create user',
    'dash.addMember': 'Add member',
    'dash.allPublications': 'Lab publications',
    'dash.quickAccess': 'Quick access',
    'dash.myResearchAxis': 'My research area',
    'dash.exploreAllAxes': 'Explore all areas',
    'dash.viewLabTeam': 'View lab team',
    'dash.consultEvents': 'View events',
    'dash.manageUsers': 'Manage users',
    'dash.viewStatistics': 'View statistics',
    'dash.auditLog': 'Audit log',
    'dash.systemSettings': 'System settings',
    'dash.superadminDashboard': 'SuperAdmin Dashboard — LIMTIC',
    'dash.pendingPublications': 'Pending publications',
    'dash.noPendingPublications': 'No pending publications',
    'dash.recentActivity': 'Recent activity',
    'dash.adminDashboard': 'Dashboard — Admin',
    'dash.manageLabContent': 'Manage publications, events and lab members',
    'dash.pendingPublicationsCount': 'Pending publications',
    'dash.activeMembers': 'Active members',
    'dash.quickActions': 'Quick actions',
    'dash.managePublications': 'Manage publications',
    'dash.manageEvents': 'Manage events',
    'dash.manageMembers': 'Manage members',
    'dash.manageAxes': 'Manage areas',
    'dash.expectedParticipants': 'expected participants',

    // Profile
    'profile.title': 'My profile',
    'profile.personalInfo': 'Personal information',
    'profile.firstName': 'First name',
    'profile.lastName': 'Last name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.role': 'Role',
    'profile.bio': 'Biography',
    'profile.researchInterests': 'Research interests',
    'profile.academicInfo': 'Academic information',
    'profile.supervisor': 'Supervisor',
    'profile.thesisSupervisor': 'Thesis supervisor',
    'profile.thesisTitle': 'Thesis title',
    'profile.myThesis': 'My thesis',
    'profile.myProject': 'My project',
    'profile.projectTitle': 'Project title',
    'profile.enrollmentYear': 'Enrollment year',
    'profile.enrollmentLabel': 'Enrollment',
    'profile.academicYear': 'Academic year',
    'profile.promotionLabel': 'Cohort',
    'profile.speciality': 'Speciality',
    'profile.masterSpeciality': 'Master\'s speciality',
    'profile.office': 'Office',
    'profile.updateSuccess': 'Profile updated successfully',
    'profile.updateProfile': 'Update profile',
    'profile.profilePhoto': 'Profile photo',
    'profile.changePhoto': 'Change photo',
    'profile.attachedAxis': 'Affiliated research area',

    // Users Management
    'users.title': 'Users Management',
    'users.manageUsers': 'Manage user accounts',
    'users.createUser': 'Create user',
    'users.editUser': 'Edit user',
    'users.totalUsers': 'Total users',
    'users.activeUsers': 'Active',
    'users.pendingUsers': 'Pending',
    'users.searchPlaceholder': 'Search for a user...',
    'users.noUsers': 'No users found',
    'users.deleteConfirm': 'Delete this user',
    'users.deleteMessage': 'Are you sure you want to delete this user?',
    'users.usersRegistered': 'registered users',
    'users.total': 'Total',
    'users.researchers': 'Researchers',
    'users.phdStudents': 'PhD Students',
    'users.masters': 'Master\'s Students',
    'users.visitors': 'Visitors',
    'users.inactive': 'Inactive',
    'users.searchByNameEmail': 'Search by name or email...',
    'users.user': 'User',
    'users.role': 'Role',
    'users.specialization': 'Specialization',
    'users.status': 'Status',
    'users.lastLogin': 'Last login',
    'users.actions': 'Actions',
    'users.activate': 'Activate',
    'users.deactivate': 'Deactivate',
    'users.active': 'Active',
    'users.since': 'Since',
    'users.userCreatedAs': 'User created as Visitor. Configure their role and information next.',
    'users.step1': 'Step 1/2: Basic information',
    'users.step2': 'Step 2/2: Role and specific information',
    'users.firstName': 'First name',
    'users.lastName': 'Last name',
    'users.password': 'Password',
    'users.confirmPassword': 'Confirm password',
    'users.next': 'Next',
    'users.finish': 'Finish',
    'users.userRole': 'User role',
    'users.visitor': 'Visitor (read-only access)',
    'users.master': 'Master\'s Student',
    'users.phd': 'PhD Student',
    'users.researcher': 'Researcher',
    'users.admin': 'Admin',
    'users.superAdmin': 'SuperAdmin',
    'users.researchAxis': 'Research area',
    'users.selectAxis': 'Select a research area',
    'users.academicProfiles': 'Academic profiles (optional)',
    'users.orcid': 'ORCID',
    'users.googleScholar': 'Google Scholar',
    'users.researchGate': 'ResearchGate',
    'users.linkedin': 'LinkedIn',
    'users.personalWebsite': 'Personal website',
    'users.enrollmentYear': 'Academic year',
    'users.supervisor': 'Supervisor',
    'users.selectSupervisor': 'Select a supervisor',
    'users.thesisTitle': 'Thesis subject',
    'users.projectTitle': 'Project subject',
    'users.fillAllFields': 'Please fill in all required fields',
    'users.passwordRequired': 'Password is required',
    'users.userModified': 'User modified successfully!',
    'users.userConfigured': 'User configured successfully!',
    'users.userDeleted': 'User deleted',
    'users.userActivated': 'activated',
    'users.userDeactivated': 'deactivated',
    'users.deleteUserConfirm': 'Delete user',
    'users.deleteUserMessage': 'Are you sure you want to delete',
    'users.irreversible': 'This action is irreversible.',
    'users.defaultVisitor': 'User will be created by default with role',
    'users.configureNext': 'You can configure their role and specific information in the next step.',
    'users.modifyUser': 'Modify user',
    'users.specificInfo': 'Modify specific information',
    'users.configureUser': 'Configure user',
    'users.rank': 'Academic rank',
    'users.rankPlaceholder': 'e.g. Associate Professor, Professor...',
    'users.errorOccurred': 'An error occurred',
    'users.invalidYear': 'Invalid enrollment year',
    'users.fillRequiredFields': 'Please fill in all required fields',

    // Supervisions (Encadrements)
    'supervision.title': 'My Supervisions',
    'supervision.phd': 'PhD Students',
    'supervision.master': 'Master\'s Students',
    'supervision.add': 'Add Supervision',
    'supervision.details': 'Details',
    'supervision.studentProfile': 'Student Profile',
    'supervision.close': 'Close',
    'supervision.enrolled': 'Enrolled in',
    'supervision.promotion': 'Cohort',
    'supervision.thesisTitle': 'Thesis subject',
    'supervision.projectTitle': 'Project subject',
    'supervision.none': 'No supervisions in this category',
    'supervision.selectType': 'Select supervision type',
    'supervision.addSupervision': 'Add supervision',
    'supervision.phdStudent': 'PhD Student',
    'supervision.phdDescription': 'Supervise a PhD student',
    'supervision.masterStudent': 'Master\'s Student',
    'supervision.masterDescription': 'Supervise a Master\'s student',
    'supervision.selectStudent': 'Select student',
    'supervision.chooseStudent': 'Choose a student',
    'supervision.thesisSubject': 'Thesis subject',
    'supervision.projectSubject': 'Project subject',
    'supervision.researchSubject': 'Research subject title...',
    'supervision.enrollmentYear': 'Enrollment year',
    'supervision.academicYear': 'Cohort',
    'supervision.modifySupervision': 'Modify supervision',
    'supervision.supervisionModified': 'Supervision modified successfully',
    'supervision.supervisionDeleted': 'Supervision deleted',
    'supervision.deleteSupervision': 'Delete supervision',
    'supervision.deleteMessage': 'Are you sure you want to remove',
    'supervision.fromSupervisions': 'from your supervisions? This action is irreversible.',
    'supervision.supervisionAdded': 'added successfully',
    'supervision.publications': 'publication',
    'supervision.publications_plural': 'publications',

    // Publications Page
    'pubPage.title': 'Scientific Publications',
    'pubPage.subtitle': 'Discover our published research work',
    'pubPage.breadcrumb': 'Home / Publications',
    'pubPage.total': 'Total',
    'pubPage.journals': 'Journals',
    'pubPage.conferences': 'Conferences',
    'pubPage.searchPlaceholder': 'Search by title, author or venue...',
    'pubPage.noPublications': 'No publications found',
    'pubPage.noResults': 'No results match your search criteria',
    'pubPage.viewDetails': 'View details',
    'pubPage.typePublication': 'Publication type',
    'pubPage.journalArticles': 'Journal articles',
    'pubPage.ranking': 'Ranking',
    'pubPage.q1': 'Q1',
    'pubPage.q2': 'Q2',
    'pubPage.coreAStar': 'CORE A*',
    'pubPage.coreA': 'CORE A',
    'pubPage.year': 'Year',
    'pubPage.axis': 'Research area',
    'pubPage.aiAxis': 'Artificial Intelligence',
    'pubPage.securityAxis': 'Computer Security',
    'pubPage.systemsAxis': 'Distributed Systems',
    'pubPage.visionAxis': 'Computer Vision',
    'pubPage.journalArticle': 'Journal article',
    'pubPage.conference': 'Conference',

    // Events Page
    'eventPage.title': 'Events',
    'eventPage.subtitle': 'Discover our seminars, workshops and conferences',
    'eventPage.breadcrumb': 'Home / Events',
    'eventPage.upcoming': 'Upcoming',
    'eventPage.ongoing': 'Ongoing',
    'eventPage.past': 'Past',
    'eventPage.photos': 'Photos',
    'eventPage.noEvents': 'No events',
    'eventPage.comeBackLater': 'Come back later to discover our next events',
    'eventPage.speakers': 'speaker',
    'eventPage.speakers_plural': 'speakers',
    'eventPage.viewDetails': 'View details',
    'eventPage.photosAvailable': 'Photos available',
    'eventPage.seminar': 'SEMINAR',
    'eventPage.workshop': 'WORKSHOP',
    'eventPage.conference': 'CONFERENCE',
    'eventPage.studyDay': 'STUDY DAY',

    // Statistics
    'stats.title': 'Statistics',
    'stats.overview': 'Laboratory overview',
    'stats.totalPublications': 'Total Publications',
    'stats.thisYear': 'This year',
    'stats.activeMembers': 'Active Members',
    'stats.upcomingEvents': 'Upcoming Events',
    'stats.researchAxes': 'Research areas',
    'stats.publicationsByYear': 'Publications by year',
    'stats.publicationsByType': 'Publications by type',
    'stats.publicationsByAxis': 'Publications by area',
    'stats.topAuthors': 'Most productive authors',

    // Audit
    'audit.title': 'Audit log',
    'audit.systemActivity': 'System activity and history',
    'audit.action': 'Action',
    'audit.user': 'User',
    'audit.details': 'Details',
    'audit.timestamp': 'Timestamp',
    'audit.searchPlaceholder': 'Search in audit...',

    // Axes de recherche
    'axes.title': 'Research Areas',
    'axes.ourAxes': 'Our Research Areas',
    'axes.discoverDomains': 'Discover our domains of expertise and innovation',
    'axes.manageAxes': 'Research Areas Management',
    'axes.createAxis': 'Create area',
    'axes.editAxis': 'Edit area',
    'axes.viewDetails': 'View details',
    'axes.members': 'Members',
    'axes.publicationsCount': 'publications',
    'axes.themes': 'Research themes',
    'axes.responsible': 'Head',
    'axes.relatedPublications': 'Related publications',
    'axes.breadcrumb': 'Home / Research Areas',
    'axes.activeAxes': 'Active areas',
    'axes.researchers': 'Researchers',
    'axes.exploreAxes': 'Explore LIMTIC laboratory research areas',
    'axes.viewPublications': 'View publications',
    'axes.totalMembers': 'Total members',
    'axes.totalPublications': 'Total publications',
    'axes.searchPlaceholder': 'Search for an area, theme or head...',
    'axes.searchPlaceholderShort': 'Search for an area or theme...',
    'axes.noAxesFound': 'No areas found for',
    'axes.noAxesFoundGeneric': 'No areas found',
    'axes.noResults': 'No results match your criteria',
    'axes.axisNotFound': 'Area not found',
    'axes.backToAxes': 'Back to research areas',
    'axes.axisHead': 'Area head',
    'axes.axisMembers': 'Area members',
    'axes.axisPublications': 'Area publications',
    'axes.themesTitle': 'Research themes',
    'axes.explorePublications': 'Explore publications',
    'axes.viewAllPublications': 'View all publications',
    'axes.scientificPublications': 'Scientific publications',
    'axes.myAxis': 'My area',
    'axes.myAxisAttachment': 'My affiliated area',
    'axes.myThesisAxis': 'My thesis area',
    'axes.youAreAttached': 'You are affiliated with this area',
    'axes.youAreAttachedThesis': 'You are affiliated with this area through your thesis',
    'axes.axesCount': 'Research areas',
    'axes.manageLabAxes': 'Manage laboratory research areas',
    'axes.axisDeleted': 'Area deleted successfully',
    'axes.deleteAxis': 'Delete this research area',
    'axes.deleteMessage': 'Are you sure you want to delete',
    'axes.deleteWarning': 'This action is irreversible and will affect',
    'axes.membersAnd': 'members and',
    'axes.createAxisTitle': 'Create a research area',
    'axes.editAxisTitle': 'Edit research area',
    'axes.axisTitle': 'Title',
    'axes.description': 'Description',
    'axes.descriptionPlaceholder': 'Detailed description of the research area...',
    'axes.responsibleSelect': 'Select a head',
    'axes.thematics': 'Themes',
    'axes.thematicsPlaceholder': 'Type a theme and press Enter',
    'axes.addTheme': 'Add',
    'axes.color': 'Color',
    'axes.colorBlue': 'Blue',
    'axes.colorRed': 'Red',
    'axes.colorTeal': 'Teal',
    'axes.colorGreen': 'Green',
    'axes.colorOrange': 'Orange',
    'axes.axisCreated': 'Area created successfully!',
    'axes.axisModified': 'Area modified successfully!',
    'axes.errorLoading': 'Error loading areas',
    'axes.tryAgainLater': 'Please try again later',
    'axes.notAssigned': 'Not assigned',
    'axes.viewProfile': 'View profile',

    // Contact
    'contact.title': 'Contact Us',
    'contact.name': 'Full name',
    'contact.email': 'Email',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.send': 'Send message',
    'contact.messageSent': 'Message sent successfully!',
    'contact.address': 'Address',
    'contact.phone': 'Phone',
    'contact.followUs': 'Follow us',
    'contact.getInTouch': 'Get in touch',
    'contact.contactInfo': 'Contact information',

    // Login & Auth
    'login.title': 'Login',
    'login.secure': 'Secure area',
    'login.secureBackoffice': 'LIMTIC back-office login',
    'login.password': 'Password',
    'login.forgotPassword': 'Forgot password?',
    'login.rememberMe': 'Remember me',
    'login.submit': 'Sign in',
    'login.backToHome': 'Back to home',
    'login.testAccounts': 'Test accounts:',
    'login.connecting': 'Connecting...',
    'login.connectionSuccess': 'Connection successful!',
    'login.connectionError': 'Connection error',
    'forgotPassword.title': 'Forgot password',
    'forgotPassword.enterEmail': 'Enter your email',
    'forgotPassword.sendCode': 'Send code',
    'forgotPassword.enterCode': 'Enter code',
    'forgotPassword.verify': 'Verify',
    'forgotPassword.verification': 'Verification',
    'forgotPassword.newPassword': 'New password',
    'forgotPassword.newPasswordTitle': 'New password',
    'forgotPassword.confirmPassword': 'Confirm password',
    'forgotPassword.resetPassword': 'Reset',
    'forgotPassword.success': 'Success',
    'forgotPassword.successMessage': 'Your password has been reset',
    'forgotPassword.backToLogin': 'Back to login',
    'forgotPassword.emailSubtitle': 'Enter your email to receive a verification code',
    'forgotPassword.otpSubtitle': 'A 6-digit code has been sent to',
    'forgotPassword.passwordSubtitle': 'Choose a new secure password',
    'forgotPassword.resendCode': 'Resend code',
    'forgotPassword.emailAddress': 'Email address',
    'forgotPassword.verifying': 'Verifying...',
    'forgotPassword.verifyCode': 'Verify code',
    'forgotPassword.sending': 'Sending...',
    'forgotPassword.backToLogin2': 'Back to login',
    'forgotPassword.enter6Digits': 'Enter the 6-digit code',
    'forgotPassword.changeEmail': 'Change email',
    'forgotPassword.resetting': 'Resetting...',
    'forgotPassword.passwordPlaceholder': 'Minimum 8 characters',
    'forgotPassword.confirmPlaceholder': 'Retype password',
    'forgotPassword.passwordRequirements': 'Password must be at least 8 characters',
    'forgotPassword.newCodeSent': 'A new code has been sent',
    'forgotPassword.errorEmail': 'Please enter your email address',
    'forgotPassword.errorCode': 'Please enter the 6-digit code',
    'forgotPassword.errorInvalidCode': 'Invalid code.',
    'forgotPassword.errorFields': 'Please fill in all fields',
    'forgotPassword.errorPasswordMatch': 'Passwords do not match',
    'forgotPassword.errorPasswordLength': 'Password must be at least 8 characters',
    'forgotPassword.codeSent': 'A verification code has been sent to your email',
    'forgotPassword.codeVerified': 'Code verified successfully',
    'forgotPassword.passwordResetSuccess': 'Password reset successfully',
    'forgotPassword.loginNow': 'Login now',
    'forgotPassword.redirecting': 'You will be redirected to the login page...',

    // Theme
    'theme.dark': 'Dark mode',
    'theme.light': 'Light mode',

    // Footer
    'footer.quickLinks': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.followUs': 'Follow us',
    'footer.legal': 'Legal notice',
    'footer.privacy': 'Privacy',
    'footer.backToTop': 'Back to top',
    'footer.allRights': 'All rights reserved.',

    // Common UI
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.modify': 'Modify',
    'common.create': 'Create',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.filters': 'Filters',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.year': 'Year',
    'common.type': 'Type',
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.success': 'Success',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.view': 'View',
    'common.viewAll': 'View all',
    'common.seeAll': 'See all',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.update': 'Update',
    'common.send': 'Send',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.all': 'All',
    'common.none': 'None',
    'common.other': 'Other',
    'common.optional': 'Optional',
    'common.required': 'Required',
    'common.select': 'Select',
    'common.selected': 'Selected',
    'common.total': 'Total',
    'common.showing': 'Showing',
    'common.of': 'of',
    'common.results': 'results',
    'common.noResults': 'No results',
    'common.noData': 'No data',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'fr';
  });

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.fr] || key;
  };

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
